### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kuragehimekurara1** [Mips96/SuDokuL#2]
I would like to translate SuDokuL into Japanese. Does SuDokuL support translation?  I accidentally closed the first issue later.  I am terribly sorry.

**Comment by Mode8fx** [comment]
Don't worry about it! However, SuDokuL doesn't natively support translation. It could be added, but to be honest, I just don't think it's worth the amount of work it would take; the only English required to actually play involves navigating the short menu. But you're free to mess around with the source code and try it yourself (if you do this, it would be much easier to create a separate executable for each language; just saying).

**Comment by kuragehimekurara1** [comment]
Thank you for telling me about it.
